# Generated by Django 5.1.3 on 2024-11-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='GenresModel',
        ),
    ]
