# Generated by Django 5.1.3 on 2024-11-28 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewmodels',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Valores abaixo de 0 nao são permitidos.'), django.core.validators.MaxValueValidator(5, 'Valores acima de 5 não são permitidos.')]),
        ),
        migrations.AlterField(
            model_name='reviewmodels',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
