# Generated by Django 5.1.3 on 2024-11-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorsmodel',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('Brazil', 'Brasil')], max_length=100, null=True),
        ),
    ]
