# Generated by Django 5.1.3 on 2024-11-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0002_actorsmodel_nationality'),
        ('genres', '0002_rename_genres_genresmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('resume', models.TextField(blank=True, null=True)),
                ('release_data', models.DateField(blank=True, null=True)),
                ('actors', models.ManyToManyField(related_name='movie_actors', to='actors.actorsmodel')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_genre', to='genres.genresmodel')),
            ],
        ),
    ]
